interfaces_list:
  - name: Ethernet0/0
  - name: Ethernet0/2
    ip: 10.4.2.14/30
  - name: Ethernet0/3
    ip: 10.4.2.18/30
  - name: Ethernet0/1
    ip: 5.8.5.1/30
  - name: Loopback0
    ip: 5.5.5.5/24