interfaces_list:
  - name: Ethernet0/0
  - name: Ethernet0/1
    ip: 10.4.2.2/30
  - name: Ethernet0/2
    ip: 10.4.2.5/30
  - name: Ethernet0/3
    ip: 10.4.2.9/30
  - name: Ethernet1/0
    ip: 10.4.2.17/30
  - name: Ethernet1/1
    ip: 2.6.2.1/30
  - name: Ethernet1/2
    ip: 2.7.2.1/30